# Use the official Node.js 20 image as a parent image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy your Next.js blog's package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application's source code from your host to your container's working directory
COPY . .

# Expose port 3000 to the host, so you can access your app
EXPOSE 3000

# Define the command to run your application
CMD ["npm", "run", "dev"]
